DROP TYPE IF EXISTS category;

CREATE TYPE category AS ENUM (
  'Front-End',
  'Back-End',
  'Database',
  'Misc.'
);

DROP TABLE IF EXISTS categories CASCADE;

CREATE TABLE categories (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  category_name category NOT NULL UNIQUE
);

DROP TABLE IF EXISTS subcategories CASCADE;

CREATE TABLE subcategories (
  id TEXT NOT NULL,
  category_id INTEGER REFERENCES categories(id) NOT NULL,
  subcategory_name TEXT NOT NULL
);

DROP TABLE IF EXISTS notes CASCADE;

CREATE TABLE notes (
  id TEXT NOT NULL,
  subcategory_id INTEGER REFERENCES subcategories(id) ON DELETE CASCADE NOT NULL,
  content TEXT NOT NULL
);
