DROP TYPE IF EXISTS category;

CREATE TYPE category AS ENUM (
  'Front-End',
  'Back-End',
  'Database',
  'Misc.'
);

DROP TABLE IF EXISTS categories CASCADE;

CREATE TABLE categories (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  category_name category NOT NULL UNIQUE
);

DROP TABLE IF EXISTS subcategories CASCADE;

CREATE TABLE subcategories (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  category_id INTEGER REFERENCES categories(id) NOT NULL,
  subcategory_name TEXT NOT NULL
);

DROP TABLE IF EXISTS notes CASCADE;

CREATE TABLE notes (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  subcategory_id INTEGER REFERENCES subcategories(id) ON DELETE CASCADE NOT NULL,
  content TEXT NOT NULL
);

INSERT INTO categories (category_name)
values
('Front-End'),
('Back-End'),
('Database'),
('Misc.');

INSERT INTO subcategories (category_id, subcategory_name)
values
('1', 'Fundamentals'),
('1', 'React'),
('2', 'Node.js'),
('3', 'DBeaver'),
('4', 'Big O Notation');

INSERT INTO notes (subcategory_id, content)
VALUES
('1', 'Test'),
('1', 'Test 2'),
('2', 'Re'),
('2', 'Act'),
('3', 'Express the best!'),
('4', 'DBeaver is also handy'),
('5', 'Biiiiig O!');
